### PR TITLE
[Persistence Service] Support delete and update for annotations

### PR DESCRIPTION
**Pull request by papadako**
Hope it is ok. Have not update the tests though, although I checked it locally.

### CODE REVIEW

**Comment by papadako** [comment]
It seems to fail in github but I do not understand why.

**Comment by schlegel** [comment]
I will look into that. I think thats a wrong configuration of the release plugin

**Comment by papadako** [comment]
Can you please check this before making the 1.1.6 release? It would be nice to have it if it is valid.

**Comment by schlegel** [comment]
We are currently working on a automatic release configuration for Anno4j. After that we will immediately look into this pull request and release a new version. Delete and Update of annotations are top priorities for us. Sorry for the delay, but after CI configuration the release cycle can be much shorter.

**Comment by papadako** [comment]
Hi! Any news on this one?

**Pull request closed without merging**
