### PR TITLE
[getTriples] Person and Software now return the whole information use…

### PR DESCRIPTION
**Pull request by papadako**
Override getTriples for Person and Software so that getTriples in Annotation returns the whole information regarding the software and person.

### CODE REVIEW

**Comment by schlegel** [comment]
Hi @papadako,
we just reviewed your pull request. With the current architecture you don't have to change the interfaces to abstract classes. We allow partial implementation with "Support" classes. We implemented your proposal in the development branch (see commit 7ba370ff07503c57c559b7f2510b65d89af8aa2d). Thank you for contribution.

**Comment by papadako** [comment]
Hi everybody.
Just wanted to inform you that I merged both develop and v2-develop branches and I found a failing test in ResourceObjectTest. Seems there is a problem with the ordering of the types of agents

```
diff --git a/anno4j-core/src/test/java/com/github/anno4j/model/impl/ResourceObjectTest.java b/anno4j-core/src/test/java/com/github/anno4j/model/impl/ResourceObjectTest.java
index 64f048d..6c4b3b6 100644
--- a/anno4j-core/src/test/java/com/github/anno4j/model/impl/ResourceObjectTest.java
+++ b/anno4j-core/src/test/java/com/github/anno4j/model/impl/ResourceObjectTest.java
@@ -6,6 +6,9 @@ import com.github.anno4j.model.Annotation;
 import com.github.anno4j.model.impl.agent.Person;
 import com.github.anno4j.model.impl.agent.Software;
 import org.junit.After;
+import static org.junit.Assert.assertEquals;
+import static org.junit.Assert.assertNotEquals;
+import static org.junit.Assert.assertTrue;
 import org.junit.Before;
 import org.junit.Test;
 import org.openrdf.idGenerator.IDGenerator;
@@ -13,10 +16,6 @@ import org.openrdf.repository.RepositoryException;
 import org.openrdf.repository.object.ObjectConnection;
 import org.openrdf.rio.RDFFormat;

-import static org.junit.Assert.assertEquals;
-import static org.junit.Assert.assertNotEquals;
-import static org.junit.Assert.assertTrue;
-
 /**
  * Created by schlegel on 05/10/15.
  */
@@ -194,8 +193,8 @@ public class ResourceObjectTest {

         String output = an.getTriples(RDFFormat.JSONLD);

-        String jsonldPerson = " \"@type\" : [ \"https://github.com/anno4j/ns#Agent\", \"http://xmlns.com/foaf/0.1/Person\" ],\n" +
-                "  \"http://xmlns.com/foaf/0.1/name\" : [ {\n" +
+        String jsonldPerson = " \"@type\" : [ \"http://xmlns.com/foaf/0.1/Person\", \"https://github.com/anno4j/ns#Agent\" ],\n"
+                +                "  \"http://xmlns.com/foaf/0.1/name\" : [ {\n" +
                 "    \"@value\" : \"PersonAgentName\"\n" +
                 "  } ],\n" +
                 "  \"http://xmlns.com/foaf/0.1/nick\" : [ {\n" +
@@ -204,8 +203,8 @@ public class ResourceObjectTest {

         assertTrue(output.contains(jsonldPerson));

-        String jsondldSoftware = " \"@type\" : [ \"https://github.com/anno4j/ns#Agent\", \"http://www.w3.org/ns/prov/SoftwareAgent\" ],\n" +
-                "  \"http://xmlns.com/foaf/0.1/homepage\" : [ {\n" +
+        String jsondldSoftware = " \"@type\" : [ \"http://www.w3.org/ns/prov/SoftwareAgent\", \"https://github.com/anno4j/ns#Agent\" ],\n"
+                +                "  \"http://xmlns.com/foaf/0.1/homepage\" : [ {\n" +
                 "    \"@value\" : \"www.example.org\"\n" +
                 "  } ],\n" +
                 "  \"http://xmlns.com/foaf/0.1/name\" : [ {\n" +

```

**Comment by schlegel** [comment]
hi @papadako 
we forgot to inform you. when we released anno4j 2.0 the develop branch became the "2.0". hence the v2-develop is obsolete and will be deleted. we added v1-develop only for major fixes if somebody still uses v1.

**Comment by papadako** [comment]
hi @schlegel 
But there are a number of commits in v2-develop commited by @AEisenkolb which are not present in develop. Hope that they will be merged.

**Comment by schlegel** [comment]
hi @papadako,
thank you very much for that info! we merged the missing commits in develop. v2-develop will be deleted after that

**Pull request closed without merging**
